"""Exact compact parity-network simulator for online frontier-node ranking.

The hot path is intentionally narrower than the repository's general
Clifford+T simulator.  It supports signed unit-coefficient phase-polynomial
cores generated by CNOT, T, and T-dagger gates.  A compact state contains only
an invertible GF(2) row basis, an emitted-term bit set, and a CNOT count.

No CircuitDAG, Clifford tableau/frame, Pauli-rotation word, dense unitary, or
general canonicalization payload is constructed while training.  A single
final witness can be replayed through the authoritative full simulator for
independent certification.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from functools import lru_cache
from typing import Literal, Sequence

GateName = Literal["H", "CNOT", "T", "TDG"]


@dataclass(frozen=True, slots=True)
class CompactGate:
    """One operation in a reconstructed compact witness."""

    name: GateName
    qubits: tuple[int, ...]
    term_index: int | None = None

    def __post_init__(self) -> None:
        if self.name in {"H", "T", "TDG"}:
            if len(self.qubits) != 1:
                raise ValueError(f"{self.name} requires one qubit")
        elif self.name == "CNOT":
            if len(self.qubits) != 2 or self.qubits[0] == self.qubits[1]:
                raise ValueError("CNOT requires distinct control and target")
        else:  # pragma: no cover - defensive runtime validation
            raise ValueError(f"unsupported compact gate {self.name!r}")

        is_phase = self.name in {"T", "TDG"}
        if is_phase != (self.term_index is not None):
            raise ValueError("term_index is required exactly for T/TDG")


@dataclass(frozen=True, slots=True)
class SignedParityTarget:
    """Target in the signed unit-coefficient parity-network normal form.

    ``terms`` contains distinct ``(parity_mask, sign)`` pairs.  A sign of +1
    emits T and -1 emits T-dagger when the corresponding parity is exposed on
    a wire.  The searched core emits every term exactly once and restores the
    identity linear basis.  Optional fixed prefix/suffix gates are outside the
    learned action space.
    """

    name: str
    num_qubits: int
    terms: tuple[tuple[int, int], ...]
    fixed_prefix: tuple[CompactGate, ...] = ()
    fixed_suffix: tuple[CompactGate, ...] = ()

    def __post_init__(self) -> None:
        if not self.name:
            raise ValueError("target name must be nonempty")
        if not 1 <= self.num_qubits <= 3:
            raise ValueError("compact CPU profile supports one to three qubits")
        if len(self.terms) > 63:
            raise ValueError("at most 63 phase terms are supported")

        masks = [mask for mask, _ in self.terms]
        if len(masks) != len(set(masks)):
            raise ValueError("target parity masks must be distinct")
        for mask, sign in self.terms:
            if not 0 < mask < (1 << self.num_qubits):
                raise ValueError("target parity mask is outside the register")
            if sign not in {-1, +1}:
                raise ValueError("phase sign must be +1 or -1")
        for operation in (*self.fixed_prefix, *self.fixed_suffix):
            if any(q < 0 or q >= self.num_qubits for q in operation.qubits):
                raise ValueError("fixed-shell gate is outside the register")

    @property
    def identity_basis(self) -> tuple[int, ...]:
        return tuple(1 << q for q in range(self.num_qubits))

    @property
    def full_emitted_mask(self) -> int:
        return (1 << len(self.terms)) - 1

    @property
    def term_index_by_parity(self) -> dict[int, int]:
        return {parity: index for index, (parity, _) in enumerate(self.terms)}

    def is_goal(self, state: "CompactState") -> bool:
        return (
            state.basis_rows == self.identity_basis
            and state.emitted_mask == self.full_emitted_mask
        )

    def full_witness(self, core: Sequence[CompactGate]) -> tuple[CompactGate, ...]:
        return (*self.fixed_prefix, *core, *self.fixed_suffix)


@dataclass(frozen=True, slots=True)
class CompactState:
    """Immutable exact semantic/resource state used in the training hot path."""

    basis_rows: tuple[int, ...]
    emitted_mask: int
    cnot_count: int
    last_action_code: int = 0  # 0=root, 1=phase, 2=CNOT

    @classmethod
    def initial(cls, num_qubits: int) -> "CompactState":
        return cls(tuple(1 << q for q in range(num_qubits)), 0, 0, 0)

    @property
    def num_qubits(self) -> int:
        return len(self.basis_rows)

    @property
    def phase_count(self) -> int:
        return self.emitted_mask.bit_count()

    @property
    def gate_count(self) -> int:
        return self.phase_count + self.cnot_count

    def semantic_key(self) -> tuple[tuple[int, ...], int]:
        """Exact continuation identity without normalization or hashing."""

        return self.basis_rows, self.emitted_mask


@dataclass(slots=True)
class CompactNode:
    """Parent-linked witness record; children do not copy a circuit DAG."""

    state: CompactState
    parent: "CompactNode | None" = None
    action: CompactGate | None = None
    record_id: int = -1
    active: bool = True
    cached_features: object | None = None


class CompactFrontier:
    """Persistent open records with exact scalar dominance.

    For one fixed target, phase count is encoded by semantic identity and total
    gate count equals phase count plus CNOT count.  Thus a smaller CNOT count
    soundly dominates a record with the same ``(basis, emitted_terms)`` key.
    """

    def __init__(self) -> None:
        self._next_record_id = 0
        self._active: dict[int, CompactNode] = {}
        self._best_cnot: dict[tuple[tuple[int, ...], int], int] = {}
        self._active_by_key: dict[tuple[tuple[int, ...], int], CompactNode] = {}
        self.duplicate_rejected = 0
        self.dominated_retired = 0
        self.reopened = 0
        self.peak_size = 0

    def insert(self, node: CompactNode) -> bool:
        key = node.state.semantic_key()
        previous = self._best_cnot.get(key)
        if previous is not None and previous <= node.state.cnot_count:
            self.duplicate_rejected += 1
            return False

        old_active = self._active_by_key.get(key)
        if old_active is not None and old_active.active:
            old_active.active = False
            self._active.pop(old_active.record_id, None)
            self.dominated_retired += 1
        elif previous is not None:
            self.reopened += 1

        self._best_cnot[key] = node.state.cnot_count
        node.record_id = self._next_record_id
        self._next_record_id += 1
        node.active = True
        self._active[node.record_id] = node
        self._active_by_key[key] = node
        self.peak_size = max(self.peak_size, len(self._active))
        return True

    def remove_for_expansion(self, node: CompactNode) -> None:
        if not node.active or self._active.get(node.record_id) is not node:
            raise KeyError("selected compact record is no longer active")
        node.active = False
        del self._active[node.record_id]
        key = node.state.semantic_key()
        if self._active_by_key.get(key) is node:
            del self._active_by_key[key]

    def nodes(self) -> tuple[CompactNode, ...]:
        """Return active records in deterministic record-ID order."""

        return tuple(self._active[index] for index in sorted(self._active))

    def __len__(self) -> int:
        return len(self._active)

    @property
    def archive_size(self) -> int:
        return len(self._best_cnot)


def _apply_cnot_rows(
    rows: tuple[int, ...], control: int, target: int
) -> tuple[int, ...]:
    mutable = list(rows)
    mutable[target] ^= mutable[control]
    return tuple(mutable)


@lru_cache(maxsize=8)
def basis_distance_to_identity(num_qubits: int) -> dict[tuple[int, ...], int]:
    """Exact minimum directed-CNOT distance from each basis to identity."""

    if not 1 <= num_qubits <= 3:
        raise ValueError("distance table supports one to three qubits")
    identity = tuple(1 << q for q in range(num_qubits))
    queue: deque[tuple[int, ...]] = deque((identity,))
    distance = {identity: 0}
    while queue:
        rows = queue.popleft()
        next_distance = distance[rows] + 1
        for control in range(num_qubits):
            for target in range(num_qubits):
                if control == target:
                    continue
                child = _apply_cnot_rows(rows, control, target)
                if child not in distance:
                    distance[child] = next_distance
                    queue.append(child)
    return distance


class CompactParityProblem:
    """Deterministically enumerate all legal compact one-gate continuations.

    The policy never chooses a gate.  It chooses one persistent frontier
    record; this problem then creates every legal T/T-dagger and directed CNOT
    child.  A memoized exact reachability predicate removes only prefixes with
    no terminal suffix inside ``max_cnot``.
    """

    schema_version = "compact-signed-parity-problem-v1"

    def __init__(self, target: SignedParityTarget, *, max_cnot: int) -> None:
        if isinstance(max_cnot, bool) or not isinstance(max_cnot, int) or max_cnot < 0:
            raise ValueError("max_cnot must be a non-negative integer")
        self.target = target
        self.max_cnot = max_cnot
        self.max_core_gates = len(target.terms) + max_cnot
        self._term_index = target.term_index_by_parity
        self._term_sign = tuple(sign for _, sign in target.terms)
        self._basis_distance = basis_distance_to_identity(target.num_qubits)
        self._can_reach = lru_cache(maxsize=None)(self._can_reach_uncached)
        if not self.can_reach(self.initial_state()):
            raise ValueError("target is unreachable within max_cnot")

    def initial_state(self) -> CompactState:
        return CompactState.initial(self.target.num_qubits)

    def is_goal(self, state: CompactState) -> bool:
        return self.target.is_goal(state)

    def remaining_terms(self, state: CompactState) -> int:
        return len(self.target.terms) - state.phase_count

    def basis_distance(self, state: CompactState) -> int:
        return self._basis_distance[state.basis_rows]

    def exposed_remaining_terms(self, state: CompactState) -> int:
        count = 0
        for parity in state.basis_rows:
            index = self._term_index.get(parity)
            if index is not None and not state.emitted_mask & (1 << index):
                count += 1
        return count

    def can_reach(self, state: CompactState) -> bool:
        return self._can_reach(
            state.basis_rows,
            state.emitted_mask,
            state.cnot_count,
        )

    def _can_reach_uncached(
        self,
        rows: tuple[int, ...],
        emitted_mask: int,
        cnot_count: int,
    ) -> bool:
        if rows == self.target.identity_basis and emitted_mask == self.target.full_emitted_mask:
            return True
        if cnot_count > self.max_cnot:
            return False
        if self._basis_distance[rows] > self.max_cnot - cnot_count:
            return False

        # Phase transitions increase popcount; CNOT transitions increase the
        # count.  The recursion is acyclic and finite.
        for parity in rows:
            index = self._term_index.get(parity)
            if index is None:
                continue
            bit = 1 << index
            if emitted_mask & bit:
                continue
            if self._can_reach(rows, emitted_mask | bit, cnot_count):
                return True

        if cnot_count == self.max_cnot:
            return False
        next_count = cnot_count + 1
        for control in range(self.target.num_qubits):
            for destination in range(self.target.num_qubits):
                if control == destination:
                    continue
                child_rows = _apply_cnot_rows(rows, control, destination)
                if self._basis_distance[child_rows] > self.max_cnot - next_count:
                    continue
                if self._can_reach(child_rows, emitted_mask, next_count):
                    return True
        return False

    def legal_actions(self, state: CompactState) -> tuple[CompactGate, ...]:
        actions: list[CompactGate] = []
        for qubit, parity in enumerate(state.basis_rows):
            index = self._term_index.get(parity)
            if index is None or state.emitted_mask & (1 << index):
                continue
            name: GateName = "T" if self._term_sign[index] > 0 else "TDG"
            actions.append(CompactGate(name, (qubit,), index))

        if state.cnot_count < self.max_cnot:
            for control in range(self.target.num_qubits):
                for destination in range(self.target.num_qubits):
                    if control != destination:
                        actions.append(CompactGate("CNOT", (control, destination)))
        return tuple(actions)

    def transition(self, state: CompactState, action: CompactGate) -> CompactState | None:
        if action.name in {"T", "TDG"}:
            assert action.term_index is not None
            index = action.term_index
            if index < 0 or index >= len(self.target.terms):
                return None
            qubit = action.qubits[0]
            parity, sign = self.target.terms[index]
            if state.basis_rows[qubit] != parity:
                return None
            if state.emitted_mask & (1 << index):
                return None
            expected = "T" if sign > 0 else "TDG"
            if action.name != expected:
                return None
            return CompactState(
                state.basis_rows,
                state.emitted_mask | (1 << index),
                state.cnot_count,
                1,
            )

        if action.name == "CNOT":
            if state.cnot_count >= self.max_cnot:
                return None
            control, destination = action.qubits
            if not (0 <= control < self.target.num_qubits):
                return None
            if not (0 <= destination < self.target.num_qubits) or control == destination:
                return None
            return CompactState(
                _apply_cnot_rows(state.basis_rows, control, destination),
                state.emitted_mask,
                state.cnot_count + 1,
                2,
            )
        return None

    def expand(self, node: CompactNode) -> tuple[CompactNode, ...]:
        children: list[CompactNode] = []
        for action in self.legal_actions(node.state):
            state = self.transition(node.state, action)
            if state is None or not self.can_reach(state):
                continue
            children.append(CompactNode(state=state, parent=node, action=action))
        return tuple(children)

    def metadata(self) -> dict[str, object]:
        return {
            "schema_version": self.schema_version,
            "target": self.target.name,
            "num_qubits": self.target.num_qubits,
            "phase_terms": [list(term) for term in self.target.terms],
            "max_cnot": self.max_cnot,
            "max_core_gates": self.max_core_gates,
            "basis_graph_vertices": len(self._basis_distance),
            "searched_gates": ["CNOT", "T", "TDG"],
            "fixed_prefix": [operation.name for operation in self.target.fixed_prefix],
            "fixed_suffix": [operation.name for operation in self.target.fixed_suffix],
            "excluded_training_hot_path": [
                "CircuitDAG",
                "Clifford tableau/frame",
                "Pauli rotations",
                "general semantic canonicalization",
                "dense-unitary certification",
            ],
        }


def reconstruct_core_witness(node: CompactNode) -> tuple[CompactGate, ...]:
    reverse: list[CompactGate] = []
    current: CompactNode | None = node
    while current is not None:
        if current.action is not None:
            reverse.append(current.action)
        current = current.parent
    reverse.reverse()
    return tuple(reverse)


def phase_truth_table(target: SignedParityTarget) -> tuple[int, ...]:
    """Target phase exponents modulo eight on all Boolean assignments."""

    values: list[int] = []
    for assignment in range(1 << target.num_qubits):
        exponent = 0
        for parity, sign in target.terms:
            exponent += sign * ((assignment & parity).bit_count() & 1)
        values.append(exponent % 8)
    return tuple(values)


def toffoli_compact_target() -> SignedParityTarget:
    """CCX as a fixed H(q2) shell around the seven-term CCZ core."""

    return SignedParityTarget(
        name="toffoli-3-fixed-H-shell-ccz-core",
        num_qubits=3,
        terms=(
            (0b001, +1),
            (0b010, +1),
            (0b100, +1),
            (0b011, -1),
            (0b101, -1),
            (0b110, -1),
            (0b111, +1),
        ),
        fixed_prefix=(CompactGate("H", (2,)),),
        fixed_suffix=(CompactGate("H", (2,)),),
    )


def materialize_authoritative_state(solution: CompactNode, target: SignedParityTarget):
    """Replay one final compact witness through the repository's full state.

    Imports are local so training never imports or updates the full symbolic
    pipeline.  The returned state is suitable for the independent dense
    ``SimulatorCertificationEngine``.
    """

    from circuit.circuit_state import CircuitState
    from circuit.dag import CircuitDAG
    from circuit.gate import Gate
    from ckt_types import ResourceBudget
    from enums import GateType

    core = reconstruct_core_witness(solution)
    witness = target.full_witness(core)
    t_count = sum(operation.name in {"T", "TDG"} for operation in witness)
    cnot_count = sum(operation.name == "CNOT" for operation in witness)
    budget = ResourceBudget(
        max_t_count=t_count,
        max_depth=len(witness),
        max_gates=len(witness),
        max_two_qubit_count=cnot_count,
    )
    state = CircuitState(CircuitDAG(target.num_qubits), budget)
    for operation in witness:
        gate_type = getattr(GateType, operation.name)
        if not state.apply_gate(Gate(gate_type, operation.qubits)):
            raise AssertionError("compact witness failed authoritative replay")
    state.validate_consistency()
    return state
